# Generated by Django 4.1.7 on 2023-06-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.CharField(max_length=10)),
                ('intensity', models.CharField(max_length=10)),
                ('sector', models.CharField(max_length=256)),
                ('topic', models.CharField(max_length=256)),
                ('insight', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=1000)),
                ('region', models.CharField(max_length=256)),
                ('start_year', models.CharField(max_length=10)),
                ('impact', models.CharField(max_length=10)),
                ('added', models.CharField(max_length=100)),
                ('published', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=256)),
                ('relevance', models.CharField(max_length=10)),
                ('pestle', models.CharField(max_length=256)),
                ('source', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('likelihood', models.CharField(max_length=10)),
            ],
        ),
    ]
